name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'eivl-1.0.0.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README.md LICENSE'
    - name: Upload Release
      uses: ncipollo/release-action@main
      with:
        allowUpdates: true
        artifacts: "eivl-1.0.0.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "1.0.0"
        commit: "main"
