name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: ncipollo/release-action@main
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: "release"